--- #YAML:1.0
name:                Language-Functional
version:             0.04
abstract:            a module which makes Perl slightly more functional
license:             perl
author:              
    - Leon Brocard <acme@astray.com>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
